#!/bin/sh

cd $HOME
[ -f dotfiles/.bash_profile ]  && ln -sb dotfiles/.bash_profile .
[ -f dotfiles/.bashrc ]        && ln -sb dotfiles/.bashrc .
[ -f dotfiles/.bashrc_custom ] && ln -sb dotfiles/.bashrc_custom .
[ -f dotfiles/.screenrc ]      && ln -sb dotfiles/.screenrc .
[ -f dotfiles/.gitconfig ]     && ln -sb dotfiles/.gitconfig .

# setup emacs
if [ -d dotfiles/.emacs.d ]; then
  [ -L .emacs.d ] && rm .emacs.d
  [ -d .emacs.d ] && mv .emacs.d .emacs.d~
  ln -sf dotfiles/.emacs.d .
fi

# Setup directories for private applications and tools.
# The .local/bin directory is pulled from the git repo.
# The bin directory is created locally.
# Both are exported to PATH by the standard .bash_profile
if [ -d dotfiles/.local ]; then
  [ -L .local ] && rm .local
  [ -d .local ] && mv .local .local~
  ln -sf dotfiles/.local .
fi
[ ! -d bin ]                   && mkdir bin

# Install heroku-client
if [ -f /etc/fedora-release ]; then
  command -v heroku > /dev/null || sudo yum -y install rubygem-heroku
fi
